service: campanas-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  environment:
    DB_HOST: localhost
    DB_USER: root
    DB_PASSWORD: ""
    DB_NAME: messages

functions:
  listCampaigns:
    handler: src/handlers/campaignHandlers.listCampaigns
    events:
      - http:
          path: campaigns
          method: get

  createCampaign:
    handler: src/handlers/campaignHandlers.createCampaign
    events:
      - http:
          path: campaigns
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env
  serverless-offline:
    httpPort: 3000
